name: Build

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
      - name: Build
        run: |
          npm ci
          npm run tauri build
      - name: Zip
        run: |
          cd scripts/zip
          npm ci
          cd ../..
          node scripts/zip/index.mjs
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./src-tauri/target/release/bundle/msi/*.msi
            *.zip
  build-mac:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
      - name: Build
        run: |
          npm ci
          npm run tauri -- build --target universal-apple-darwin
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
